services:
  bot:
    image: hyperf0rm/guild_queue_bot:latest
    restart: always
    ports:
      - "8001:8081"
    volumes:
      - ./backups:/app/backups
      - ./credentials.json:/app/credentials.json:ro
      - ./token.json:/app/token.json
      - ./pwobs_auth.json:/app/pwobs_auth.json
    env_file:
      - .env
    environment:
      - WEB_PORT=8081

  frontend:
    image: hyperf0rm/guild_queue_bot:frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - bot
